
download_links:
  genome: https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_chromosome_files/TAIR10_chr_all.fas.gz
  gtf: https://www.arabidopsis.org/download_files/Genes/Araport11_genome_release/Araport11_GTF_genes_transposons.current.gtf.gz
  description: ftp://ftp.arabidopsis.org/Genes/TAIR10_genome_release/TAIR10_functional_descriptions_20140331.txt
  alias: ftp://ftp.arabidopsis.org/Genes/gene_aliases_20140331.txt
