

rule all:
    input:
        "rawdata/IRGSPb5.fa.masked.gz"


rule download_genome:
    output:
        "rawdata/IRGSPb5.fa.masked.gz"
    params:
        outdir = "rawdata",
        url = "https://rapdb.dna.affrc.go.jp/download/archive/build5/IRGSPb5.fa.masked.gz"
    shell:
        "mkdir -p {params.outdir} ; cd {params.outdir} ; wget {params.url}"

