from pathlib import Path

configfile: "config.yaml"

rule all:
    input:
        "rawdata/IRGSP-1.0_representative_annotation_2023-09-07.tsv.gz",
        ["genome/os.rap-db.genome.fa" + suffix for suffix in [".amb", ".ann", ".bwt", ".pac", ".sa"]],
        "star_index",
        ["osdb/OS_refGene.txt", "osdb/OS_refGeneMrna.fa"],
        "id_converter.txt"

rule download_genome:
    output:
        "rawdata/IRGSP-1.0_genome.fasta.gz"
    params:
        url = config["download_links"]["genome"]
    shell:
        "cd rawdata ; wget {params.url}"

rule download_gff:
    output:
        locus = "rawdata/IRGSP-1.0_representative/locus.gff",
        transcripts = "rawdata/IRGSP-1.0_representative/transcripts.gff",
        transcripts_exon = "rawdata/IRGSP-1.0_representative/transcripts_exon.gff"
    params:
        url = config["download_links"]["gff"]
    shell:
        "cd rawdata ; wget {params.url} ; tar -xzf IRGSP-1.0_representative_2023-09-07.tar.gz"

rule download_kasalath:
    output:
        "rawdata/kasalath_genome/all.fasta"
    params:
        url = config["download_links"]["kasalath"]
    shell:
        "cd rawdata ; wget {params.url} ; tar -xzf kasalath_genome.tar.gz"

rule download_annotation:
    output:
        "rawdata/IRGSP-1.0_representative_annotation_2023-09-07.tsv.gz"
    params:
        url = config["download_links"]["annotation"]
    shell:
        "cd rawdata ; wget {params.url}"

rule download_id_converter:
    output:
        "rawdata/RAP-MSU_2023-09-07.txt.gz"
    params:
        url = config["download_links"]["id_converter"]
    shell:
        "cd rawdata ; wget {params.url}"

rule genome:
    input:
        "rawdata/IRGSP-1.0_genome.fasta.gz"
    output:
        fa = "genome/os.rap-db.genome.fa",
        fai = "genome/os.rap-db.genome.fa.fai",
        dict = "genome/os.rap-db.genome.dict"
    shell:
        '''
        gzip -dc {input} > {output.fa}
        samtools faidx {output.fa}
        gatk CreateSequenceDictionary -R {output.fa}
        '''

rule bwa:
    input:
        "genome/os.rap-db.genome.fa"
    output:
        ["genome/os.rap-db.genome.fa" + suffix for suffix in [".amb", ".ann", ".bwt", ".pac", ".sa"]]
    shell:
        "bwa index {input}"

rule make_gtf:
    input:
        "rawdata/IRGSP-1.0_representative/transcripts.gff"
    output:
        "gtf/os.rap-db.make.gtf"
    script:
        "scripts/make_gtf.R"


rule star_index:
    input:
        fa = "genome/os.rap-db.genome.fa",
        gtf = "gtf/os.rap-db.make.gtf"
    output:
        star_index = directory("star_index")
    threads:
        20
    shell:
        '''
        STAR \
            --runThreadN {threads} \
            --runMode genomeGenerate \
            --genomeDir {output.star_index} \
            --genomeFastaFiles {input.fa} \
            --sjdbGTFfile {input.gtf} \
            --genomeSAindexNbases 13  # Adjusted base on STAR's warning.
        '''


rule annovar:
    input:
        fa = "genome/os.rap-db.genome.fa",
        gtf = "gtf/os.rap-db.make.gtf"
    output:
        refGene = "osdb/OS_refGene.txt",
        refGeneMrna = "osdb/OS_refGeneMrna.fa"
    shell:
        '''
        mkdir -p osdb
        gtfToGenePred \
            -genePredExt \
            -ignoreGroupsWithoutExons \
            {input.gtf} \
            {output.refGene}
        retrieve_seq_from_fasta.pl \
            --format refGene \
            --seqfile {input.fa} \
            {output.refGene} \
            --out {output.refGeneMrna}
        '''

rule id_converter:
    input:
        "rawdata/RAP-MSU_2023-09-07.txt.gz"
    output:
        "id_converter.txt"
    script:
        "scripts/id_converter.py"

