from pathlib import Path


rule download:
    input:
        "download_links.txt"
    output:
        fa = "rawdata/IRGSP-1.0_genome.fasta.gz",
        gff = "rawdata/IRGSP-1.0_representative/transcripts.gff",
        kasalath = "rawdata/kasalath_genome/all.fasta",
        annotation = "rawdata/IRGSP-1.0_representative_annotation_2023-09-07.tsv.gz"
    shell:
        '''
        aria2c -i {input} -c -d rawdata
        cd rawdata
        tar -xzf IRGSP-1.0_representative_2023-09-07.tar.gz
        tar -xzf kasalath_genome.tar.gz
        '''


rule genome:
    input:
        rules.download.output.fa
    output:
        fa = "genome/os.rap-db.genome.fa",
        fai = "genome/os.rap-db.genome.fa.fai",
        dict = "genome/os.rap-db.genome.dict"
    shell:
        '''
        zcat < {input} > {output.fa}
        samtools faidx {output.fa}
        gatk CreateSequenceDictionary -R {output.fa}
        '''


rule bwa:
    input:
        rules.genome.output.fa
    output:
        [rules.genome.output.fa + suffix for suffix in [".amb", ".ann", ".bwt", ".pac", ".sa"]]
    shell:
        '''
        bwa index {input}
        '''


rule make_gtf:
    input:
        rules.download.output.gff
    output:
        "gtf/os.rap-db.make.gtf"
    shell:
        '''
        Rscript scripts/make_gtf.R
        '''


rule star_index:
    input:
        fa = rules.genome.output.fa,
        gtf = rules.make_gtf.output
    output:
        star_index = directory("star_index")
    threads:
        20
    shell:
        '''
        STAR \
            --runThreadN {threads} \
            --runMode genomeGenerate \
            --genomeDir {output.star_index} \
            --genomeFastaFiles {input.fa} \
            --sjdbGTFfile {input.gtf} \
            --genomeSAindexNbases 13  # Adjusted base on STAR's warning.
        '''

rule minimap_kasalath:
    input:
        rules.download.output.kasalath
    output:
        "minimap/kasalath.mmi"
    threads:
        20
    shell:
        '''
        minimap2 -t {threads} -d {output} {input}
        '''


rule all:
    input:
        rules.genome.output,
        rules.bwa.output,
        rules.star_index.output,
        rules.minimap_kasalath.output

